export const PERSONAL = {
    SET_PERSONAL_DETAILS: 'SET_PERSONAL_DETAILS',
    SET_BANK_DETAILS: 'SET_BANK_DETAILS',
    SET_PROFESSIONAL_DETAILS: 'SET_PROFESSIONAL_DETAILS',
    SET_CURRENT_STATUS: 'SET_CURRENT_STATUS',
    SET_EXPERIENCE_DETAILS: 'SET_EXPERIENCE_DETAILS',
    SET_EDUCATIONAL_DETAILS: 'SET_EDUCATIONAL_DETAILS',
    SET_EMPLOYEEFORM: 'SET_EMPLOYEEFORM',
    USER_EDIT: 'USER_EDIT',
    USER_DELETE: 'USER_DELETE',
    DELETE_ALL: 'DELETE_ALL'
}